"""Output writers for link audit reports."""
from __future__ import annotations

import csv
import json
from dataclasses import asdict
from datetime import datetime, timezone

from .config import OUT_DIR
from .model import PageRecord


def write_all_links_json(records: list[PageRecord]) -> None:
    path = OUT_DIR / "all_links.json"
    with path.open("w", encoding="utf-8") as f:
        json.dump([asdict(r) for r in records], f, indent=2, ensure_ascii=False)
    print(f"  -> {path}  ({len(records)} records)")


def write_link_inventory_csv(records: list[PageRecord]) -> None:
    path = OUT_DIR / "link_inventory.csv"
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "url", "parent_url", "depth", "status_code", "content_type",
            "classification", "title", "keywords", "high_priority_keywords", "redirect_url",
        ])
        for r in records:
            writer.writerow([
                r.url, r.parent_url or "", r.depth, r.status_code or "",
                r.content_type or "", r.classification, r.title,
                "; ".join(r.keywords), "; ".join(r.high_priority_keywords),
                r.redirect_url or "",
            ])
    print(f"  -> {path}")


def write_broken_links_csv(records: list[PageRecord]) -> None:
    path = OUT_DIR / "broken_links.csv"
    broken = [r for r in records if r.status_code is None or r.status_code >= 400]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["url", "parent_url", "depth", "status_code", "error", "classification"])
        for r in broken:
            writer.writerow([
                r.url, r.parent_url or "", r.depth,
                r.status_code or "N/A", r.error or "", r.classification,
            ])
    print(f"  -> {path}  ({len(broken)} broken)")


def write_high_priority_csv(records: list[PageRecord]) -> None:
    path = OUT_DIR / "high_priority_links.csv"
    hi = [r for r in records if r.high_priority_keywords]
    hi.sort(key=lambda x: (-len(x.high_priority_keywords), x.url))
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "url", "parent_url", "depth", "status_code", "classification",
            "title", "high_priority_keywords", "all_keywords",
        ])
        for r in hi:
            writer.writerow([
                r.url, r.parent_url or "", r.depth, r.status_code or "",
                r.classification, r.title,
                "; ".join(r.high_priority_keywords), "; ".join(r.keywords),
            ])
    print(f"  -> {path}  ({len(hi)} high-priority)")


def _write_page_details(f, records: list[PageRecord], high_priority: bool) -> None:
    for r in records:
        if bool(r.high_priority_keywords) != high_priority:
            continue
        f.write(f"### {r.title or r.url}\n\n")
        f.write(f"- **URL:** {r.url}\n")
        f.write(f"- **Classification:** `{r.classification}`\n")
        f.write(f"- **Depth:** {r.depth}\n")
        label = "High-priority keywords" if high_priority else "Keywords"
        values = r.high_priority_keywords if high_priority else r.keywords
        f.write(f"- **{label}:** {', '.join(values)}\n")
        if high_priority:
            f.write(f"- **All keywords:** {', '.join(r.keywords)}\n")
        f.write(f"- **Parent:** {r.parent_url or 'seed'}\n")
        if r.redirect_url:
            f.write(f"- **Redirected to:** {r.redirect_url}\n")
        f.write("\n")


def write_frontier_relevant_pages(records: list[PageRecord]) -> None:
    path = OUT_DIR / "frontier_relevant_pages.md"
    relevant = [r for r in records if r.keywords]
    relevant.sort(key=lambda x: (-len(x.high_priority_keywords), -len(x.keywords), x.url))
    high_pri = [r for r in relevant if r.high_priority_keywords]

    with path.open("w", encoding="utf-8") as f:
        f.write("# Frontier-Relevant Pages\n\n")
        f.write(f"> Auto-generated by `frontier_link_audit.py` on {_now()}\n\n")
        f.write(f"**Total pages scanned:** {len(records)}  \n")
        f.write(f"**Pages with keyword hits:** {len(relevant)}  \n\n")
        f.write("## Priority Overview\n\n")
        f.write("| Priority | Count |\n|----------|-------|\n")
        f.write(f"| High (has high-signal keywords) | {len(high_pri)} |\n")
        f.write(f"| Standard (keyword match only) | {len(relevant) - len(high_pri)} |\n\n")
        f.write("---\n\n## High-Priority Pages\n\n")
        _write_page_details(f, relevant, high_priority=True)
        f.write("---\n\n## Standard-Priority Pages\n\n")
        _write_page_details(f, relevant, high_priority=False)
    print(f"  -> {path}  ({len(relevant)} relevant)")


def write_external_tools(records: list[PageRecord]) -> None:
    path = OUT_DIR / "external_tools.md"
    tool_kw = {"efctl", "scaffold"}
    tool_pages = [r for r in records if any(k in r.keywords for k in tool_kw)]

    with path.open("w", encoding="utf-8") as f:
        f.write("# External Tools & Scaffold References\n\n")
        f.write(f"> Auto-generated on {_now()}\n\n")
        if not tool_pages:
            f.write("_No pages referencing efctl or scaffold were found._\n")
        else:
            _write_tool_summary(f, tool_pages, tool_kw)
            _write_tool_details(f, tool_pages)
    print(f"  -> {path}  ({len(tool_pages)} tool pages)")


def _write_tool_summary(f, tool_pages: list[PageRecord], tool_kw: set[str]) -> None:
    f.write(f"Found **{len(tool_pages)}** pages referencing external tools.\n\n")
    f.write("| Page | Classification | Tool Keywords | URL |\n")
    f.write("|------|---------------|---------------|-----|\n")
    for r in tool_pages:
        matched = [k for k in tool_kw if k in r.keywords]
        title = r.title[:60] if r.title else r.url[:60]
        f.write(f"| {title} | `{r.classification}` | {', '.join(matched)} | {r.url} |\n")


def _write_tool_details(f, tool_pages: list[PageRecord]) -> None:
    f.write("\n---\n\n### Details\n\n")
    for r in tool_pages:
        f.write(f"#### {r.title or r.url}\n\n")
        f.write(f"- **URL:** {r.url}\n")
        f.write(f"- **Classification:** `{r.classification}`\n")
        f.write(f"- **All keywords:** {', '.join(r.keywords)}\n")
        f.write(f"- **Parent:** {r.parent_url or 'seed'}\n\n")


def write_classification_summary(records: list[PageRecord]) -> None:
    classes: dict[str, int] = {}
    for r in records:
        classes[r.classification] = classes.get(r.classification, 0) + 1

    print("\n  Classification breakdown:")
    for cls, count in sorted(classes.items(), key=lambda x: -x[1]):
        print(f"    {cls:<25} {count:>4}")


def write_outputs(records: list[PageRecord]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    print("\nWriting outputs:")
    write_all_links_json(records)
    write_link_inventory_csv(records)
    write_broken_links_csv(records)
    write_high_priority_csv(records)
    write_frontier_relevant_pages(records)
    write_external_tools(records)
    write_classification_summary(records)


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
